apiVersion: v1
kind: ServiceAccount
metadata:
  name: github
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: github-token
  annotations:
    kubernetes.io/service-account.name: github
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github
subjects:
- kind: ServiceAccount
  name: github
  namespace: mizotakhteh
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
