apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mizotakhteh-crt
  namespace: mizotakhteh
spec:
  secretName: mizotakhteh-tls
  dnsNames:
    - api.mizotakhteh.ml
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer